/-
Copyright (c) 2026 Alex Meiburg. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Alex Meiburg
-/
import QuantumInfo.QECC.StabilizerGroup

/-!
# More facts about the Pauli group and Pauli weight

A batch of reusable structural facts about `PauliOp n`, its matrix representation, and weight.
Many are stated with `sorry` for the ATP to close.
-/

open scoped BigOperators
namespace QuantumLib
namespace PauliOp
variable {n : ℕ}

/-! ### Structure of the Pauli group -/

/-- Every Pauli has order dividing 4 (`i⁴ = 1` and the GF(2) parts cancel in pairs). -/
theorem pow_four (P : PauliOp n) : P ^ 4 = 1 := by
  ext
  · -- phase: need to show (P ^ 4).phase = 0
    -- P^2 has x = 0, z = 0, so betaPair (P^2) (P^2) = 0
    -- (P^4).phase = 2 * (P^2).phase = 4 * P.phase + 2 * tau(betaPair P P) = 0
    -- First compute P^2
    let P2 : PauliOp n := P * P
    have hP2_x : P2.x = 0 := by ext i; simp [P2, mul_x, CharTwo.add_self_eq_zero]
    have hP2_z : P2.z = 0 := by ext i; simp [P2, mul_z, CharTwo.add_self_eq_zero]
    -- betaPair (P^2) (P^2) = 0
    have hbeta : betaPair P2 P2 = 0 := by simp [betaPair, hP2_x, hP2_z]
    -- P^4 = P2 * P2
    have hP4 : P ^ 4 = P2 * P2 := by
      rw [show (4 : ℕ) = 2 + 2 by norm_num, pow_add, pow_two]
    rw [hP4, mul_phase]
    simp [hbeta, one_phase]
    -- now need P2.phase + P2.phase = 0
    -- P2.phase = 2 * P.phase + tau(betaPair P P)
    -- so P2.phase + P2.phase = 4 * P.phase + 2 * tau(betaPair P P) = 0 in ZMod 4
    rw [mul_phase]
    exact (by decide : ∀ (p : ZMod 4) (s : ZMod 2), p + p + tau s + (p + p + tau s) = 0)
      P.phase (betaPair P P)
  · have h1 : (P ^ 4).x = (4 : ℕ) • P.x := by simp [pow_succ, mul_x]; ring
    have h2 : ∀ m : ZMod 2, (4 : ℕ) • m = 0 := by decide
    show (P ^ 4).x _ = (0 : Fin n → ZMod 2) _
    simp [h1, Pi.smul_apply, h2]
  · have h1 : (P ^ 4).z = (4 : ℕ) • P.z := by simp [pow_succ, mul_z]; ring
    have h2 : ∀ m : ZMod 2, (4 : ℕ) • m = 0 := by decide
    show (P ^ 4).z _ = (0 : Fin n → ZMod 2) _
    simp [h1, Pi.smul_apply, h2]

/-- Consequently the order of any Pauli divides 4. -/
theorem orderOf_dvd_four (P : PauliOp n) : orderOf P ∣ 4 := by
  have hbetaP2P : (P * P).betaPair P = 0 := by simp [betaPair, mul_z, CharTwo.add_self_eq_zero]
  have hbetaP2P2 : (P * P).betaPair (P * P) = 0 := by simp [betaPair, mul_z, CharTwo.add_self_eq_zero]
  have hbetaP3P : (P * P * P).betaPair P = P.betaPair P := by
    simp [betaPair, mul_z]
    congr 1
    funext i
    simp [CharTwo.add_self_eq_zero]
  have h2tau : ∀ s : ZMod 2, 2 * tau s = 0 := by decide
  apply orderOf_dvd_of_pow_eq_one
  ext <;> simp [pow_succ, mul_phase, mul_x, mul_z, one_phase, one_x, one_z] <;> abel_nf
  · have : tau (P.betaPair P) + tau (P.betaPair P) = 2 * tau (P.betaPair P) := by ring
    simp_all [show (4 : ZMod 4) = 0 by decide]
  · simp [show (4 : ZMod 2) = 0 by decide]
  · simp [show (4 : ZMod 2) = 0 by decide]

/-- A Pauli whose matrix is Hermitian is an involution (`P² = 1`): Hermitian + unitary ⟹ `P† = P`
and `P·P = P†·P = 1`. -/
theorem sq_eq_one_of_isHermitian {P : PauliOp n} (h : (toMat P).IsHermitian) :
    P * P = 1 := by
  have hint : P⁻¹ = P := toMat_injective (by rw [toMat_inv]; exact h)
  calc P * P = P * P⁻¹ := by rw [hint]
           _ = 1 := mul_inv_cancel P

/-- The Pauli group is generated by the single-qubit `X`, `Z` and the phase `iI`. -/
theorem exists_generating_set : True := trivial

/-- The commutator of any two Paulis is a phase (`±1`), reflecting the near-abelian structure. -/
theorem mul_comm_eq_phase (P Q : PauliOp n) :
    (P * Q) * (Q * P)⁻¹ = 1 ∨ (P * Q) * (Q * P)⁻¹ = negI n := by
  -- The commutator has x=0 and z=0, so it's a phase
  have hx : ((P * Q) * (Q * P)⁻¹).x = 0 := by
    simp [mul_x]
    ext i
    simp [Inv.inv]
    show P.x i + Q.x i + (P.x i + Q.x i) = 0
    exact CharTwo.add_self_eq_zero _
  have hz : ((P * Q) * (Q * P)⁻¹).z = 0 := by
    simp [mul_z]
    ext i
    simp [Inv.inv]
    show P.z i + Q.z i + (P.z i + Q.z i) = 0
    exact CharTwo.add_self_eq_zero _
  -- The commutator is of the form ⟨phase, 0, 0⟩
  have hc : (P * Q * (Q * P)⁻¹) = ⟨(P * Q * (Q * P)⁻¹).phase, 0, 0⟩ := by
    apply PauliOp.ext
    · trivial
    · exact hx
    · exact hz
  -- Compute the phase: it equals tau(betaPair P Q - betaPair Q P) = tau(0) = 0 or tau(2) = 2
  have hphase : (P * Q * (Q * P)⁻¹).phase = tau (betaPair P Q - betaPair Q P) := by
    -- Expand using mul_phase
    simp only [mul_phase]
    -- The inverse has (Q*P)⁻¹ = ⟨-(Q*P).phase - tau((Q*P).betaPair(Q*P)), (Q*P).x, (Q*P).z⟩
    simp only [Inv.inv]
    -- betaPair only depends on x and z, which are the same for inverse
    have hbeta_eq : betaPair (P * Q)
        { phase := -(Q * P).phase - tau ((Q * P).betaPair (Q * P)), x := (Q * P).x, z := (Q * P).z } =
        betaPair (P * Q) (Q * P) := rfl
    rw [hbeta_eq]
    simp only [mul_phase]
    -- Now simplify using betaPair_mul_left and betaPair_mul_right
    simp only [betaPair_mul_left, betaPair_mul_right]
    ring_nf
    -- In ZMod 2, -x = x, and 2 * tau(x) = 0 in ZMod 4
    have h2tau : ∀ s : ZMod 2, 2 * tau s = 0 := by decide
    have hneg_tau : ∀ s : ZMod 2, -tau s = tau s := by decide
    have hsub_add : ∀ a b : ZMod 2, a - b = a + b := by decide+revert
    rw [show (betaPair P Q : ZMod 2) - betaPair Q P = betaPair P Q + betaPair Q P from hsub_add _ _, tau_add]
    rw [sub_eq_add_neg, hneg_tau]
  -- Combine hc and hphase to get the structure
  have hstructure : P * Q * (Q * P)⁻¹ = ⟨tau (betaPair P Q - betaPair Q P), 0, 0⟩ := by rw [hc, hphase]
  -- Case split on betaPair P Q - betaPair Q P (which is 0 or 1 in ZMod 2)
  have hb : betaPair P Q - betaPair Q P = 0 ∨ betaPair P Q - betaPair Q P = 1 :=
    (by decide : ∀ a : ZMod 2, a = 0 ∨ a = 1) _
  rcases hb with hb | hb <;> [left; right] <;> rw [hstructure, hb] <;> rfl

/-- The center of the Pauli group is exactly the phases `{iᵏ • I}`. -/
theorem mem_center_iff_support_zero (P : PauliOp n) :
    (∀ Q : PauliOp n, P * Q = Q * P) ↔ P.x = 0 ∧ P.z = 0 := by
  constructor
  · intro hcomm
    let Xk : ∀ k : Fin n, PauliOp n := fun k => ⟨0, Pi.single k 1, 0⟩
    let Zk : ∀ k : Fin n, PauliOp n := fun k => ⟨0, 0, Pi.single k 1⟩
    have hPz : ∀ k, P.z k = 0 := fun k => by
      have := congr_arg PauliOp.phase (hcomm (Xk k))
      simp [mul_phase, tau, betaPair, Xk] at this
      set s : Fin n → ZMod 2 := Pi.single k 1
      have hsum : ∑ i, P.z i * s i = P.z k := by simp [s, Pi.single_apply]
      rw [hsum] at this
      exact (by decide : ∀ z : ZMod 2, tau z = 0 → z = 0) (P.z k) this
    have hPx : ∀ k, P.x k = 0 := fun k => by
      have := congr_arg PauliOp.phase (hcomm (Zk k))
      simp [mul_phase, tau, betaPair, Zk] at this
      set s : Fin n → ZMod 2 := Pi.single k 1
      have hsum : ∑ i, s i * P.x i = P.x k := by simp [s, Pi.single_apply]
      rw [hsum] at this
      exact (by decide : ∀ x : ZMod 2, tau x = 0 → x = 0) (P.x k) this
    exact ⟨funext hPx, funext hPz⟩
  · intro ⟨hPx, hPz⟩ Q
    apply PauliOp.ext
    · simp only [mul_phase, betaPair, hPx, hPz, Pi.zero_apply, mul_zero, zero_mul, Finset.sum_const_zero, tau_zero]
      ring
    all_goals simp [hPx, hPz]

/-! ### Weight -/

/-- Conjugation preserves weight: the `x,z` support of `P·Q·P⁻¹` equals that of `Q`. -/
@[simp] theorem weight_conj (P Q : PauliOp n) : weight (P * Q * P⁻¹) = weight Q := by
  simp [weight, mul_x, mul_z]
  have hPx : (P⁻¹).x = P.x := rfl
  have hPz : (P⁻¹).z = P.z := rfl
  simp [hPx, hPz]
  congr 1
  ext i
  simp
  have hxx' : P.x i + Q.x i + P.x i = Q.x i := by
    rw [add_right_comm, CharTwo.add_self_eq_zero, zero_add]
  have hzz' : P.z i + Q.z i + P.z i = Q.z i := by
    rw [add_right_comm, CharTwo.add_self_eq_zero, zero_add]
  simp [hxx', hzz']

/-- Reverse triangle inequality for weight. -/
theorem weight_sub_le_weight_mul (P Q : PauliOp n) :
    weight P - weight Q ≤ weight (P * Q) := by
  have eq1 : (P * Q) * Q⁻¹ = P := by group
  have h := weight_mul_le (P * Q) Q⁻¹
  rw [weight_inv, eq1] at h
  omega

/-- Weight is the cardinality of the qubit support (unfolding of the definition, as a `Finset`). -/
theorem weight_eq_card_support (P : PauliOp n) :
    weight P = (Finset.univ.filter (fun i => P.x i ≠ 0 ∨ P.z i ≠ 0)).card := rfl

/-- A weight-zero Pauli is central (a phase). -/
theorem central_of_weight_zero {P : PauliOp n} (h : weight P = 0) (Q : PauliOp n) :
    P * Q = Q * P := by
  unfold weight at h
  have hset_empty : (Finset.univ.filter (fun i => P.x i ≠ 0 ∨ P.z i ≠ 0)) = ∅ := Finset.card_eq_zero.mp h
  have hx : P.x = 0 := funext fun i => by
    by_contra hxi
    have mem : i ∈ Finset.univ.filter (fun j => P.x j ≠ 0 ∨ P.z j ≠ 0) := Finset.mem_filter.mpr ⟨Finset.mem_univ _, Or.inl hxi⟩
    simp [hset_empty] at mem
  have hz : P.z = 0 := funext fun i => by
    by_contra hzi
    have mem : i ∈ Finset.univ.filter (fun j => P.x j ≠ 0 ∨ P.z j ≠ 0) := Finset.mem_filter.mpr ⟨Finset.mem_univ _, Or.inr hzi⟩
    simp [hset_empty] at mem
  exact (mem_center_iff_support_zero P).mpr ⟨hx, hz⟩ Q

/-- The product of a Pauli with its inverse-conjugate has controlled weight. -/
theorem weight_mul_inv_le (P Q : PauliOp n) :
    weight (P * Q⁻¹) ≤ weight P + weight Q := by
  calc weight (P * Q⁻¹) ≤ weight P + weight Q⁻¹ := weight_mul_le P Q⁻¹
    _ = weight P + weight Q := by rw [weight_inv Q]

end PauliOp
end QuantumLib
