/-
Copyright (c) 2025 Joseph Tooby-Smith. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joseph Tooby-Smith
-/
module

public import Physlib.Relativity.Tensors.MetricTensor
public import Physlib.Relativity.Tensors.Contraction.UnitTensorContraction
/-!

# Dual tensors

-/

@[expose] public section

namespace TensorSpecies

variable {k : Type} [RCLike k] {C : Type} {G : Type} [Group G]
    {V : C → Type} [∀ c, AddCommGroup (V c)] [∀ c, Module k (V c)]
    {basisIdx : C → Type} [∀ c, Fintype (basisIdx c)] [∀ c, DecidableEq (basisIdx c)]
    {rep : (c : C) → Representation k G (V c)} {b : (c : C) → Module.Basis (basisIdx c) k (V c)}
    {S : TensorSpecies k C G V basisIdx rep b}

namespace Tensor

/-- The linear map between `S.Tensor c` and `S.Tensor (Function.update c i (S.τ (c i)))` formed by
  contracting with the metric tensor at a specific index. It is `crossToSlot` against
  `metricTensor (S.τ (c i))`, the case where the rank-2 tensor's two slots share a color. -/
noncomputable def toDualMapAtIndex : {n : ℕ} → {c : Fin n → C} → (i : Fin n) →
    S.Tensor c →ₗ[k] S.Tensor (Function.update c i (S.τ (c i)))
  | 0, _, i => i.elim0
  | _ + 1, c, i => crossToSlot i (0 : Fin 2) rfl (metricTensor (S := S) (S.τ (c i)))

/-- Dualising slot `i` twice returns the original color list: `τ (τ (c i)) = c i`, and no other
  slot moves. The color cast carried by the double-dual round trips below. -/
lemma IsReindexing.update_dual_dual {n : ℕ} (c : Fin n → C) (i : Fin n) :
    IsReindexing c (Function.update (Function.update c i (S.τ (c i))) i
      (S.τ (Function.update c i (S.τ (c i)) i))) (id : Fin n → Fin n) :=
  IsReindexing.on_id.mpr (fun j => by
    by_cases h : j = i <;> simp [h, Function.update_of_ne, τ_τ_apply])

/-- Dualising any named index twice returns the original tensor, up to the color cast generated by
the two `Function.update`s. Stated at every rank, matching the domain of `toDualMapAtIndex`. -/
lemma toDualMapAtIndex_toDualMapAtIndex {n : ℕ} {c : Fin n → C}
    (i : Fin n) (t : S.Tensor c) :
    toDualMapAtIndex (S := S) i (toDualMapAtIndex (S := S) i t) =
      permT (id : Fin n → Fin n) (IsReindexing.update_dual_dual c i) t := by
  cases n with
  | zero => exact i.elim0
  | succ nA =>
    let M₁ := metricTensor (S := S) (S.τ (c i))
    let M₂ : S.Tensor ![S.τ (S.τ (c i)), c i] :=
      permT (fun x : Fin 2 => x)
        (IsReindexing.on_id.mpr (fun j => by fin_cases j <;> simp [τ_τ_apply]))
        (metricTensor (S := S) (c i))
    -- The two dual metrics collapse to the unit tensor: `gᵃᵇ · g_cd = δ`.
    have hM : crossToEnd (S := S) (Fin.last 1) (0 : Fin 2) rfl M₁ M₂ =
        permT (id : Fin 2 → Fin 2) (IsReindexing.unitTensor_pair rfl)
          (unitTensor (S := S) (c i)) := by
      dsimp only [M₁, M₂]
      rw [crossToEnd_permT_right (Fin.last 1) (0 : Fin 2)
        (fun x : Fin 2 => x) (fun x : Fin 1 => x)
        (IsReindexing.on_id.mpr (fun i => by fin_cases i <;> simp [τ_τ_apply])) rfl]
      rw [crossToEnd_two, contrT_dual_metricTensor_metricTensor]
      simp only [Fin.isValue, Nat.reduceAdd, permT_permT, CompTriple.comp_eq]
      refine permT_congr ?_ rfl
      ext j; fin_cases j <;> rfl
    have key := crossToSlot_raise_lower_round_trip (S := S) i (M := M₁) (M' := M₂)
      (he := rfl) (ha := rfl) (hb := rfl) (hM := hM) (t := t)
    -- Reconcile the second metric's symmetric color with the mixed contraction color.
    let x := S.τ (Function.update c i (S.τ (c i)) i)
    have hmetric : metricTensor (S := S) x =
        permT (id : Fin 2 → Fin 2)
          (IsReindexing.on_id.mpr (fun j => by
            fin_cases j <;> simp [x, Function.update_self, τ_τ_apply])) M₂ := by
      dsimp only [M₂]
      rw [metricTensor_congr (by simp [x, Function.update_self, τ_τ_apply] : x = c i)]
      rw [permT_permT]
      refine permT_congr ?_ rfl
      ext j; fin_cases j <;> rfl
    rw [toDualMapAtIndex, toDualMapAtIndex]
    change crossToSlot i (0 : Fin 2) rfl (metricTensor (S := S) x)
      (crossToSlot i (0 : Fin 2) rfl M₁ t) = _
    rw [hmetric, crossToSlot_permT_right_id, key]
    simp only [permT_permT]
    refine permT_congr ?_ rfl
    funext j; simp

/-- The inverse of `toDualMapAtIndex` at the same index: dualise again, then absorb the color cast
  the two `Function.update`s generate. Absorbing it here is what makes the round trips in both
  directions cast-free. -/
noncomputable def fromDualMapAtIndex {n : ℕ} {c : Fin n → C} (i : Fin n) :
    S.Tensor (Function.update c i (S.τ (c i))) →ₗ[k] S.Tensor c :=
  permT (id : Fin n → Fin n) (IsReindexing.on_id_symm (IsReindexing.update_dual_dual c i)) ∘ₗ
  toDualMapAtIndex (S := S) (c := Function.update c i (S.τ (c i))) i

@[simp]
lemma fromDualMapAtIndex_toDualMapAtIndex {n : ℕ} {c : Fin n → C} (i : Fin n) (t : S.Tensor c) :
    fromDualMapAtIndex (S := S) i (toDualMapAtIndex (S := S) i t) = t := by
  simp [fromDualMapAtIndex, toDualMapAtIndex_toDualMapAtIndex]

@[simp]
lemma toDualMapAtIndex_fromDualMapAtIndex {n : ℕ} {c : Fin n → C} (i : Fin n)
    (t : S.Tensor (Function.update c i (S.τ (c i)))) :
    toDualMapAtIndex (S := S) i (fromDualMapAtIndex (S := S) i t) = t := by
  -- `fromDualMapAtIndex` is injective, being an identity reindexing after a dualisation which
  -- `fromDualMapAtIndex_toDualMapAtIndex` already inverts at the updated color assignment.
  have hinj : Function.Injective (fromDualMapAtIndex (S := S) (c := c) i) := by
    simp only [fromDualMapAtIndex, LinearMap.coe_comp]
    exact (permT_injective _).comp
      (Function.LeftInverse.injective (fromDualMapAtIndex_toDualMapAtIndex i))
  exact Function.LeftInverse.rightInverse_of_injective
    (fromDualMapAtIndex_toDualMapAtIndex i) hinj t

/-- Dualising a named index is `G`-equivariant. The content is the invariance of the metric tensor:
  the action must be introduced on the metric factor before the equivariance of the contraction
  applies. -/
@[simp]
lemma toDualMapAtIndex_equivariant {n : ℕ} {c : Fin n → C} (i : Fin n) (g : G) (t : S.Tensor c) :
    toDualMapAtIndex (S := S) i (g • t) = g • toDualMapAtIndex (S := S) i t := by
  cases n with
  | zero => exact i.elim0
  | succ nA =>
    rw [toDualMapAtIndex]
    conv_lhs => rw [← metricTensor_invariant (S := S) g]
    exact crossToSlot_equivariant i (0 : Fin 2) _ g _ t

/-- The linear equivalence between `S.Tensor c` and `S.Tensor (Function.update c i (S.τ (c i)))`
  formed by contracting with the metric tensor at the index `i`. Raising and lowering a named
  index are mutually inverse, so the two color assignments carry the same information. -/
noncomputable def toDualAtIndex {n : ℕ} {c : Fin n → C} (i : Fin n) :
    S.Tensor c ≃ₗ[k] S.Tensor (Function.update c i (S.τ (c i))) :=
  LinearEquiv.mk (toDualMapAtIndex i) (fromDualMapAtIndex i).toFun
    (fromDualMapAtIndex_toDualMapAtIndex i) (toDualMapAtIndex_fromDualMapAtIndex i)

end Tensor

open Tensor

end TensorSpecies
